/** Shape of site/web/public/catalog.json (generated by scripts/build_site.py). */

export type Skill = {
  id: string;
  folder: string;
  path: string;
  description: string;
  folderUrl: string;
  bundleUrl: string;
  copyCommand: string;
  search: string;
};

export type PluginRow = {
  name: string;
  description: string;
  skillCount: number;
};

export type SiteCatalog = {
  marketTitle: string;
  metaDescription: string;
  version: string | null;
  generatedAt: string;
  repository: string;
  sourceBranch: string;
  cloneUrl: string;
  repoName: string;
  marketplacePluginName: string;
  plugins: PluginRow[];
  skills: Skill[];
};
